webtalk_init -webtalk_dir C:/Users/hp/UART_Protocol/UART_Protocol.sim/sim_1/synth/func/xsim/xsim.dir/tb_UART_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jul 31 10:20:32 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3a8b7fd3-3bcc-4cd5-86cd-24c3d2276a49" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c92d6889e4af4c3e92efe780f4646a94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD PRO A8-9600B R5, 10 COMPUTE CORES 4C+6G    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2396 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "13" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "370 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "102 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2557" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "496" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "86140_KB" -context "xsim\\usage"
webtalk_transmit -clientid 137278252 -regid "" -xml C:/Users/hp/UART_Protocol/UART_Protocol.sim/sim_1/synth/func/xsim/xsim.dir/tb_UART_func_synth/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/hp/UART_Protocol/UART_Protocol.sim/sim_1/synth/func/xsim/xsim.dir/tb_UART_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/hp/UART_Protocol/UART_Protocol.sim/sim_1/synth/func/xsim/xsim.dir/tb_UART_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
